spring:
  main:
    web-application-type: NONE 
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/questionnaire-manager
    username: root
    password: password
  liquibase:
    change-log: classpath:/db/main.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false